version: '3'

services:
    portfolio:
        build: .
        ports:
            -"8000:8000"
        volumes:
            - .:/code
        environment: 
            DJANGO_ENV: development
        
    postgres:
        image: "postgres:12"