version: "3"

services:
  db_postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
      - POSTGRES_DB = ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  portfolio:
    image: aaronga19/portfolio
    ports:
      - 8000:8000
    volumes:
      - static:/Portfolio/static
      - media:/Portfolio/media
      - .:/Portfolio
    #command: gunicorn -c config/gunicorn/conf.py --bind :8000 --chdir Portfolio Portfolio.wsgi:application

    
    environment:
      - SECRET_KEY = ${SECRET_KEY}
      - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
      - DATABASE_PORT = ${DATABASE_PORT}
      - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
      - DATABASE_NAME = ${DATABASE_NAME}
      - DATABASE_USERNAME = ${DATABASE_USERNAME}
      - EMAIL = ${EMAIL}
      - PASS_EMAIL = ${PASS_EMAIL}
      - AWS_ID = ${AWS_ID}
      - AWS_ACCESS = ${AWS_ACCESS}
      - AWS_NAME = ${AWS_NAME}

    depends_on:
      - db_postgres
    
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/Portfolio/static
      - media:/Portfolio/media
    depends_on:
      - portfolio

volumes:
  .:
  postgres_data:
  static:
  media: