# Generated by Django 3.2.3 on 2021-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('company', models.CharField(default='Personal', max_length=50, verbose_name='Empresa')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'UserContact',
                'verbose_name_plural': 'UserContacts',
            },
        ),
    ]
