# Generated by Django 3.2.3 on 2021-06-02 22:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('category', models.CharField(choices=[('1', 'Desarollo de hardware'), ('2', 'Desarrollo de software'), ('3', 'Ciencia de datos'), ('4', 'Machine Learning'), ('5', 'Inteligencia Artificial')], max_length=1, verbose_name='Categoría')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('resume', models.TextField(max_length=200, verbose_name='Resumen')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('photos', models.ImageField(upload_to='images/', verbose_name='Fotos')),
                ('videos', models.FileField(upload_to='videos/', verbose_name='Videos')),
                ('anexos', models.CharField(max_length=50, verbose_name='Anexos')),
                ('code', models.URLField(unique=True, verbose_name='Código')),
                ('public', models.BooleanField(default=True, verbose_name='Público')),
                ('Favorite', models.BooleanField(default=False, verbose_name='Favorito')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('link', models.URLField(verbose_name='Link')),
                ('dependency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.dependency')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
            },
        ),
    ]
