# Generated by Django 3.2.3 on 2021-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='videos',
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto 1'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto 3'),
        ),
        migrations.AddField(
            model_name='projects',
            name='video_1',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video 1'),
        ),
        migrations.AddField(
            model_name='projects',
            name='video_2',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video 2'),
        ),
    ]
