# Generated by Django 3.2.3 on 2021-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210617_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='photo_1',
            field=models.ImageField(upload_to='images/', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
