# Generated by Django 3.2.3 on 2021-08-05 20:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210618_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardware',
            },
        ),
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name': 'Dependency', 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterField(
            model_name='dependency',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('1', 'Hardware Development'), ('2', 'Software Development'), ('3', 'Data Science'), ('4', 'Machine Learning'), ('5', 'Artificial Inteligence')], max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='code',
            field=models.URLField(unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_1',
            field=models.ImageField(upload_to='images/', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo 3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='resume',
            field=models.TextField(max_length=200, verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='projects',
            name='hardware',
            field=models.ManyToManyField(to='projects.hardware'),
        ),
    ]
